name: Check
on:
  push:
    branches:
      - main
      - workflow_check
  pull_request:
    branches:
      - main

env:
  # Emit backtraces on panics.
  RUST_BACKTRACE: full
  # Enable colors in cargo output.
  CARGO_TERM_COLOR: always
  # Use sparse index if supported.
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Install Mingw-w64
        shell: bash
        run: sudo apt install -y --no-install-recommends gcc-mingw-w64-i686

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync toolchain
        shell: bash
        run: rustup show

      - name: Run cargo fmt
        shell: bash
        run: cargo fmt --all -- --check

      - name: Run cargo check
        shell: bash
        run: RUSTFLAGS="-D warnings" cargo check --workspace

      # fails due to `_Unwind_RaiseException`
      # - name: Run cargo test
      #   shell: bash
      #   run: RUSTFLAGS="-D warnings" cargo test --workspace

      - name: Run cargo build (release)
        run: cargo build --verbose --release
        shell: bash
