name: Check
on:
  push:
    branches:
      - main
      - workflow_check
  pull_request:
    branches:
      - main

env:
  # Emit backtraces on panics.
  RUST_BACKTRACE: full
  # Enable colors in cargo output.
  CARGO_TERM_COLOR: always
  # Use sparse index if supported.
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  check-gnu:
    name: check-gnu
    runs-on: ubuntu-latest
    steps:
      - name: Install Mingw-w64
        shell: bash
        run: sudo apt install -y --no-install-recommends gcc-mingw-w64-i686

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync toolchain
        shell: bash
        run: rustup show

      - name: Run cargo fmt
        shell: bash
        run: cargo fmt --all -- --check

      - name: Run cargo check
        shell: bash
        run: RUSTFLAGS="-D warnings" cargo check --workspace --target 'i686-pc-windows-gnu'

      - name: Run cargo test
        shell: bash
        run: RUSTFLAGS="-D warnings" cargo test --workspace --target 'x86_64-unknown-linux-gnu'

      - name: Run cargo build (release)
        shell: bash
        run: cargo build --verbose --release --package 'zipfixup' --package 'zippatch' --target 'i686-pc-windows-gnu'

      - name: Run export checker
        shell: bash
        run: cargo run --package 'export-check' --target 'x86_64-unknown-linux-gnu' -- 'target/i686-pc-windows-gnu/release/zipfixup.dll'

  check-msvc:
    name: check-msvc
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync toolchain
        shell: bash
        run: rustup show

      - name: Run cargo fmt
        shell: bash
        run: cargo fmt --all -- --check

      - name: Run cargo check
        shell: bash
        run: RUSTFLAGS="-D warnings" cargo check --workspace --target 'i686-pc-windows-msvc'

      - name: Run cargo test
        shell: bash
        run: RUSTFLAGS="-D warnings" cargo test --workspace --target 'i686-pc-windows-msvc'

      - name: Run cargo build (release)
        shell: bash
        run: cargo build --verbose --release --package 'zipfixup' --package 'zippatch' --target 'i686-pc-windows-msvc'

      - name: Run export checker
        shell: bash
        run: cargo run --package 'export-check' --target 'x86_64-pc-windows-msvc' -- 'target/i686-pc-windows-msvc/release/zipfixup.dll'
